version: 2
registries:
  github-octocat:
    type: git
    url: https://github.com
    username: x-access-token
    password: "${{secrets.RUBYGEMS_SERVER_GITHUB_TOKEN}}"
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: '10:00'
    timezone: America/Los_Angeles
  pull-request-branch-name:
    separator: "-"
  commit-message:
    prefix: "üîß "
    prefix-development: "üîß "
    include: scope
  open-pull-requests-limit: 10
- package-ecosystem: gomod
  directory: "/"
  schedule:
    interval: weekly
    day: tuesday
    time: '10:00'
    timezone: America/Los_Angeles
  pull-request-branch-name:
    separator: "-"
  commit-message:
    prefix: "‚¨ÜÔ∏è "
    prefix-development: "‚¨ÜÔ∏è "
    include: scope
  open-pull-requests-limit: 10
  registries:
  - github-octocat
